<?php
	require_once('tcpdf/tcpdf.php');
	require('comun.inc');
	require('funciones.inc');
	session_start();
	date_default_timezone_set("America/Bogota");
	class MYPDF extends TCPDF 
	{
		public function Header() 
		{
			$linkbd=conectar_bd();
			$sqlr="select *from configbasica where estado='S'";
			$res=mysql_query($sqlr,$linkbd);
			while($row=mysql_fetch_row($res))
 			{
  				$nit=$row[0];
  				$rs=$row[1];
 				$nalca=$row[6];
 			}
			$this->Image('imagenes/eng.jpg',23,10,25,25);
			$this->SetFont('dejavusans','B',8);
			$this->SetY(10);
			//$pdf->RoundedRect(10, 41, 190, 24, 1.2, '1111', '');
			$this->RoundedRect(10, 10, 199, 31, 2.5,'1111','' );
			$this->Cell(0.1);
			$this->Cell(50,31,'','R',0,'L'); 
			$this->SetY(31);
			$this->Cell(0.1);
			$this->Cell(50,5,''.$rs,0,0,'C'); 
			$this->SetFont('dejavusans','B',8);
			$this->SetY(35);
			$this->Cell(0.1);
			$this->Cell(50,5,''.$nit,0,0,'C');
			$this->SetFont('dejavusans','B',14);
			$this->SetY(10);
   			$this->Cell(50.1);
    		$this->Cell(149,31,'',0,1,'C'); 
			$this->SetY(8);
    		$this->Cell(50.1);
    		$this->Cell(149,20,'COMPROBANTE EGRESO DE NOMINA',0,0,'C'); 
    		$this->SetFont('dejavusans','I',8);
			$this->SetY(27);
			$this->Cell(50.2);
			$this->multiCell(110.7,4,''.strtoupper($_POST[concepto]),'T','C');
			$this->SetFont('dejavusans','B',9);
			$this->SetY(27);
			$this->Cell(161.1);
			$this->Cell(37.8,14,'','TL',0,'L');
			$this->SetY(27);
			$this->Cell(162);
			$this->Cell(35,5,'NUMERO : '.$_POST[egreso],0,0,'L');
			$this->SetY(31);
			$this->Cell(162);
			$this->Cell(35,5,'FECHA: '.$_POST[fecha],0,0,'L');
			$this->SetY(35);
			$this->Cell(162);
			$this->Cell(35,5,'VIGENCIA: '.$_SESSION[vigencia],0,0,'L');
			$this->SetY(27);
			$this->Cell(50.2);
			$this->MultiCell(105.7,4,'',0,'L');
			$this->SetFont('times','B',10);
			$this->ln(12);		
		}
		public function Footer() 
		{
			$this->SetY(-15);
			$this->SetFont('dejavusans','I',10);
			$this->Cell(0, 10, 'Impreso por: Software SPID - G&C Tecnoinversiones SAS. - Pagina '.$this->getAliasNumPage().' de '.$this->getAliasNbPages(), 0, false, 'R', 0, '', 0, false, 'T', 'M');
		}
	}
	$pdf = new MYPDF('P','mm','Letter', true, 'UTF-8', false);
	$pdf->SetAutoPageBreak(TRUE, 20);
	$pdf->AddPage();
	$pdf->SetFont('dejavusans','B',12);
	$pdf->SetY(46);   
	$pdf->cell(125);
	$pdf->cell(27,8,'NETO A PAGAR: ',0,0,'R');
	$pdf->RoundedRect(161, 46 ,48 , 8, 2,'1111','');
	$pdf->cell(45,8,'$'.number_format($_POST[valorpagar],2),0,0,'R');
	$pdf->ln(10);
	$pdf->SetFillColor(255,255,255);
	$pdf->cell(0.2);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(35,5,'Beneficiario: ',0,0,'L',1);
	$pdf->SetFont('dejavusans','',10);
	$pdf->cell(165,5,''.substr(ucwords(strtolower($_POST[ntercero])),0,100),0,1,'L',1);
	$pdf->cell(0.2);  
	$pdf->SetFillColor(245,245,245);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(35,5,'C.C. o NIT: ',0,0,'L',1);
	$pdf->SetFont('dejavusans','',10);
	$pdf->cell(163,5,''.$_POST[tercero],0,1,'L',1);
	$pdf->SetFillColor(255,255,255);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(0.2);
	$pdf->cell(35,5,'No CxP::',0,0,'L',1);
	$pdf->SetFont('dejavusans','',10);
	$pdf->cell(40,5,''.$_POST[orden],0,0,'L',1);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(35,5,'FORMA PAGO:',0,0,'L',1);
	$pdf->SetFont('dejavusans','',9);
	$pdf->cell(40,5,''.strtoupper($_POST[tipop]),0,1,'L',1);
	$pdf->SetFillColor(245,245,245);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(35,5,'BANCO: ',0,0,'L',1);
	$pdf->SetFont('dejavusans','',9);
	$pdf->cell(91,5,''.substr(strtoupper($_POST[nbanco]),0,80),0,0,'L',1);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(15,5,'N Cta.:',0,0,'L',1);
	$pdf->SetFont('dejavusans','',10);
	$pdf->cell(35,5,''.$_POST[tcta].' '.$_POST[cb],0,1,'L',1);
	$pdf->SetFillColor(255,255,255);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(37,5,'CHEQUE/TRANSF.:',0,0,'L',1);
	$pdf->SetFont('dejavusans','',10);
	$pdf->cell(35,5,''.$_POST[ntransfe].$_POST[ncheque],0,1,'L',1);
	$pdf->SetFillColor(245,245,245);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(0.2);
	$pdf->cell(35,5,'Valor Pago:',0,0,'L',1);
	$pdf->SetFont('dejavusans','',10);
	$pdf->cell(40,5,'$'.number_format($_POST[valororden],2),0,0,'L',1);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(25,5,'Retenciones: ',0,0,'L',1);
	$pdf->SetFont('dejavusans','',10);
	$pdf->cell(35,5,'$'.number_format($_POST[retenciones],2),0,0,'L',1);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(25,5,'Neto a Pagar:',0,0,'L',1);
	$pdf->SetFont('dejavusans','',10);
	$pdf->cell(38,5,'$'.number_format($_POST[valorpagar],2),0,1,'L',1);
	$pdf->SetFillColor(255,255,255);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->cell(35,5,'Son: ',0,0,'L',1);
	$pdf->SetFont('dejavusans','',8);
	$pdf->cell(121,5,''.strtoupper($_POST[letrasegreso]),0,0,'L',1);
	$pdf->RoundedRect(10, 54 ,199 , 38, 2,'1111','' );
	$pdf->ln(8);
	$pdf->SetFillColor(222,222,222);
	$pdf->SetFont('dejavusans','B',10);
    $pdf->Cell(0.1);
    $pdf->Cell(199,5,'DETALLE EGRESO',0,0,'C',1); 
	$pdf->ln(6); 
	$pdf->SetFillColor(222,222,222);
	$pdf->SetFont('dejavusans','B',10);
	$pdf->Cell(150,5,'Concepto',0,0,'C',1);
	$pdf->Cell(1);
	$pdf->Cell(48,5,'Valor',0,1,'C',1);
	$pdf->SetFont('dejavusans','',8);
	$pdf->SetFillColor(245,245,245);
	$pdf->Cell(150,5,'SALARIO DEVENGADO ',0,0,'L',1);
	$pdf->Cell(1);
    $pdf->Cell(48,5,"$ ".number_format($_POST[salariodevengado],2,',','.'),0,1,'R',1); 
	$pdf->SetFillColor(255,255,255);
	$pdf->Cell(150,5,'PAGO SALUD EMPLEADO',0,0,'L',1);
	$pdf->Cell(1);
    $pdf->Cell(48,5,"-$ ".number_format($_POST[valorsalud],2,',','.'),0,1,'R',1);
	$pdf->SetFillColor(245,245,245);
	$pdf->Cell(150,5,'PAGO PENSION EMPLEADO',0,0,'L',1);
	$pdf->Cell(1);
    $pdf->Cell(48,5,"-$ ".number_format($_POST[valorpension],2,',','.'),0,1,'R',1);
	$pdf->SetFillColor(255,255,255);
	$pdf->Cell(150,5,'PAGO FONDO DE SOLIDARIDAD',0,0,'L',1);
	$pdf->Cell(1);
    $pdf->Cell(48,5,"-$ ".number_format($_POST[valorfondosol],2,',','.'),0,1,'R',1);
	$pdf->SetFillColor(245,245,245);
	$pdf->Cell(150,5,'PAGO FONDO DE SOLIDARIDAD',0,0,'L',1);
	$pdf->Cell(1);
    $pdf->Cell(48,5,"-$ ".number_format($_POST[valordeducciones],2,',','.'),0,1,'R',1);
	$pdf->SetFillColor(255,255,255);
	$pdf->Cell(150,5,'RETENCION EN LA FUENTE',0,0,'L',1);
	$pdf->Cell(1);
    $pdf->Cell(48,5,"-$ ".number_format(0,2,',','.'),0,1,'R',1);
	$pdf->SetFillColor(245,245,245);
	$pdf->Cell(150,5,'REDONDEO DECIMAL',0,0,'L',1);
  	$redondeo=$_POST[valorpagar]-($_POST[salariodevengado]-$_POST[valorsalud]-$_POST[valorpension]-$_POST[valorfondosol]-$_POST[valordeducciones]);
	$pdf->Cell(1);
    $pdf->Cell(48,5,"$ ".number_format($redondeo,2,',','.'),0,1,'R',1);
	$pdf->SetFillColor(222,222,222);
	$pdf->SetFont('dejavusans','B',8);
	$pdf->Cell(150,5,'VALOR NETO A PAGAR',0,0,'L',1);
	$pdf->Cell(1);
    $pdf->Cell(48,5,"$ ".number_format($_POST[valorpagar],2),0,1,'R',1);
	$linkbd=conectar_bd();
	$sqlr="select *from configbasica where estado='S'";
	$res=mysql_query($sqlr,$linkbd);
	while($row=mysql_fetch_row($res))
 	{
  		$nit=$row[0];
  		$rs=$row[1];
  		$nalca=$row[6];
 	}
	$sqlr="select *from  tesoparametros where estado='S'";
	$res=mysql_query($sqlr,$linkbd);
	while($row=mysql_fetch_row($res)){$teso=$row[4];}
	$pdf->ln(32);
	$pdf->SetFont('times','B',9);
	$pdf->Cell(50);	
	$pdf->Cell(80,4,strtoupper($nalca),'T',1,'C');
	$pdf->Cell(50);
	$pdf->Cell(80,4,'ALCALDE '.strtoupper($rs),'',1,'C');
	$pdf->ln(29);
	$pdf->SetFont('times','B',9);
	$pdf->Cell(50);
	$pdf->Cell(80,4,''.strtoupper($teso),'T',1,'C');
	$pdf->Cell(50);
	$pdf->Cell(80,4,'JEFE TESORERIA','',1,'C');
	$pdf->ln(29);
	$pdf->Cell(50);
	$pdf->SetFont('times','B',9);
	$pdf->Cell(80,4,''.strtoupper($_POST[ntercero]).' CC/NIT '.$_POST[tercero],'T',1,'C');
	$pdf->Cell(50);
	$pdf->SetFont('times','B',9);
	$pdf->Cell(80,4,'BENEFICIARIO','',1,'C');
	$pdf->SetFont('times','',10);
	$pdf->cell(25);
	$pdf->Cell(55,4,'',0,1,'L'); 
	
	$pdf->Output();
	
?>